# Generated by Django 3.2.6 on 2022-01-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP_Twitter', '0002_alter_tweet_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='polarity',
            field=models.CharField(default='', max_length=12),
        ),
    ]
