# Generated by Django 3.2.6 on 2022-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP_Twitter', '0003_tweet_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='polarity_index',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4),
        ),
    ]
