# Generated by Django 3.2.6 on 2022-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP_Twitter', '0005_alter_tweet_polarity_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.CharField(max_length=50),
        ),
    ]
