# Generated by Django 3.2.6 on 2022-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP_Twitter', '0006_alter_topic_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='raw_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
